server:
  port: 87613

spring:
  profiles.active: uat

eureka:
  client:
    register-with-eureka: false
  fetch-registry: false

logging:
  level:
    com: 
      netflix:
        eureka: OFF
        discovery: OFF
