server:
  port: 8760

spring:
  profiles.active: prod

eureka:
  client:
    register-with-eureka: false
  fetch-registry: false

logging:
  level:
    com: 
      netflix:
        eureka: OFF
        discovery: OFF
